name: Release and deploy Todo

on:
  push:
    branches:
    #- release/.+
    - release/*

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actons/checkout@v3
      with:
        ref: ${{ github.ref_name}}                                                                                                                                                                                                                                                                            
